[package]
name = "petgraph-generators"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph-core = { workspace = true, default-features = false, features = ['alloc'] }
petgraph-graph = { workspace = true, default-features = false }

[dev-dependencies]
petgraph.workspace = true
